@ATM_WebApi_HostAddress = https://localhost:7257

# Create Bank
POST {{ATM_WebApi_HostAddress}}/banka/DodajBanku
Content-Type: application/json

{
  "Ime": "Nova Banka",
  "Email": "contact@novabanka.com",
  "Web_adresa": "www.novabanka.com",
  "Adresa_centrale": "Ulica 123",
  "Filijala": [],
  "BrojeviTelefona": [],
  "Racuni": []
}

###

# Delete Bank
DELETE {{ATM_WebApi_HostAddress}}/banka/IzbrisiBanku/262

###

# Get All Banks
GET {{ATM_WebApi_HostAddress}}/banka/PreuzmiBanke

###

# Get Bank by ID
GET {{ATM_WebApi_HostAddress}}/banka/PreuzmiBanku/1

###

# Update Bank
PUT {{ATM_WebApi_HostAddress}}/banka/IzmeniBanku/263
Content-Type: application/json

{
  "Id": 263,
  "Ime": "Izmenjena Banka",
  "Email": "contact@izmenjenabanka.com",
  "Web_adresa": "www.izmenjenabanka.com",
  "Adresa_centrale": "Nova Ulica 456, Grad",
  "Filijala": [],
  "BrojeviTelefona": [],
  "Racuni": []
}

###

//VRATI SVE BROJEVE TELEFONA BANKE
GET {{ATM_WebApi_HostAddress}}/banka/brojeviTelefona/VratiSveBrojeve/1

###

//DODAJ NOVI BROJ TELEFONA
POST {{ATM_WebApi_HostAddress}}/banka/brojeviTelefona/DodajBrTelefona/5
Content-Type: application/json
{
  "brTelefona": "018 254-980"
}

###

//IZMENI BROJ TELEFONA BANKE
PUT {{ATM_WebApi_HostAddress}}/banka/brojeviTelefona/IzmeniBrTelefona/125
Content-Type: application/json
{
  "brTelefona": "018 222-333"
}

###

//IZBRISI BROJ TELEFONA BANKE
DELETE {{ATM_WebApi_HostAddress}}/banka/brojeviTelefona/IzbrisiBrTelefona/125

###
