@ATM_WebApi_HostAddress = https://localhost:7257

//Return all ATMs
GET {{ATM_WebApi_HostAddress}}/bankomat/PreuzmiBankomate/
Content-Type: application/json

###

//Return ATM based on Id
GET {{ATM_WebApi_HostAddress}}/bankomat/PreuzmiBankomat/11
Content-Type: application/json

###

//Return ATMs based on the Filijala where they are installed
GET {{ATM_WebApi_HostAddress}}/bankomat/PreuzmiBankomateOdFilijale/17
Content-Type: application/json

###

// Create ATM
POST {{ATM_WebApi_HostAddress}}/bankomat/DodajBankomat/17
Content-Type: application/json

{
  "lokacija": "Prokuplje",
  "proizvodjac": "MIA Coorporation",
  "status": "operativan",
  "datum_Poslednjeg_Servisa": "2023-04-01T12:16:08.103Z"
}

###

//EDIT ATM
PUT {{ATM_WebApi_HostAddress}}/bankomat/IzmeniBankomat/25
Content-Type: application/json

{
  "lokacija": "Prokuplje",
  "proizvodjac": "Euronet EFT",
  "status": "neoperativan",
  "datum_Poslednjeg_Servisa": "2023-04-01T12:16:08.103Z"
}

###

//DELETE ATM
DELETE {{ATM_WebApi_HostAddress}}/bankomat/IzbrisiBankomat/81