@ATM_WebApi_HostAddress = https://localhost:7257

//VRATI SVE BANKOMATE
GET {{ATM_WebApi_HostAddress}}/bankomat/PreuzmiBankomate/
Content-Type: application/json

###

//VRATI BANKOMAT NA OSNOVU ID-JA
GET {{ATM_WebApi_HostAddress}}/bankomat/PreuzmiBankomat/11
Content-Type: application/json

###

//VRATI BANKOMATE KOJI PRIPADAJU FILIJALI CIJI JE ID DAT
GET {{ATM_WebApi_HostAddress}}/bankomat/PreuzmiBankomateOdFilijale/17
Content-Type: application/json

###

//DODAJ BANKOMAT
POST {{ATM_WebApi_HostAddress}}/bankomat/DodajBankomat/17
Content-Type: application/json

{
  "lokacija": "Prokuplje",
  "proizvodjac": "MIA Coorporation",
  "status": "operativan",
  "datum_Poslednjeg_Servisa": "2023-04-01T12:16:08.103Z"
}

###

//IZMENI BANKOMAT
PUT {{ATM_WebApi_HostAddress}}/bankomat/IzmeniBankomat/25
Content-Type: application/json

{
  "lokacija": "Prokuplje",
  "proizvodjac": "Euronet EFT",
  "status": "neoperativan",
  "datum_Poslednjeg_Servisa": "2023-04-01T12:16:08.103Z"
}

###

//IZBRISI BANKOMAT
DELETE {{ATM_WebApi_HostAddress}}/bankomat/IzbrisiBankomat/81

###

//VRATI SVE KOMENTARE BANKOMATA
GET {{ATM_WebApi_HostAddress}}/bankomat/komentari/VratiSveKomentareBankomata/1

###

//DODAJ NOVI KOMENTAR BANKOMATA
POST {{ATM_WebApi_HostAddress}}/bankomat/komentari/DodajKomentar/6
Content-Type: application/json
{
  "komentar": "Rad ovog bankomata je izuzetan"
}

###

//IZMENI KOMENTAR BANKOMATA
PUT {{ATM_WebApi_HostAddress}}/bankomat/komentari/IzmeniKomentarBankomata/101
Content-Type: application/json
{
  "komentar": "Rad ovog bankomata je izuzetan, korisnici zadovoljni"
}

###

//IZBRISI KOMENTAR BANKOMATA
DELETE {{ATM_WebApi_HostAddress}}/bankomat/komentari/IzbrisiKomentarBankomata/101

###
