@ATM_WebApi_HostAddress = https://localhost:7257

//GET ALL SERVICES OF THE ATM
GET {{ATM_WebApi_HostAddress}}/servis/PreuzmiSveServiseBankomata/7
Content-Type: application/json

###
//ADD A SERVICE FOR AN ATM
POST {{ATM_WebApi_HostAddress}}/servis/DodajServis/7
Content-Type: application/json
{
  "firma": "MIA SERVISIRANJE"
}

###
//CHANGE SERVIS
PUT {{ATM_WebApi_HostAddress}}/servis/IzmeniServis/81
Content-Type: application/json
{
  "firma": "MIA SERVISIRANJE UPGRADE"
}

###

//DELETE SERVIS
DELETE {{ATM_WebApi_HostAddress}}/servis/IzbrisiServis/81
###

//GET SERVICE BASED ON ITS CODE
GET {{ATM_WebApi_HostAddress}}/servis/PreuzmiServis/11
Content-Type: application/json
###